### ISSUE TITLE
[BUG] Ignite Nodes disconnecting every now and then

### ISSUE THREAD

**Issue by toszo** [epiphany-platform/epiphany#1415]
**Describe the bug**
We were noticing our Ignite nodes disconnecting occasionally on the Dev cluster. So far twice on May 19, 2020.

Servers going from 2->1:

```
[23:03:23] Data Regions Configured:
[23:03:23]   ^-- default [initSize=256.0 MiB, maxSize=12.6 GiB, persistenceEnabled=false]
[23:03:36] Topology snapshot [ver=15376, servers=1, clients=17, CPUs=24, offheap=13.0GB, heap=22.0GB]
[23:03:36]   ^-- Node [id=D53D63B2-3AD3-47E9-B4CE-3E7B9EB2BB79, clusterState=ACTIVE]
[23:03:36] Data Regions Configured:
[23:03:36]   ^-- default [initSize=256.0 MiB, maxSize=12.6 GiB, persistenceEnabled=false]
[23:03:48] Topology snapshot [ver=15377, servers=2, clients=17, CPUs=32, offheap=25.0GB, heap=23.0GB]
[23:03:48]   ^-- Node [id=D53D63B2-3AD3-47E9-B4CE-3E7B9EB2BB79, clusterState=ACTIVE]
[23:03:48] Data Regions Configured:
[23:03:48]   ^-- default [initSize=256.0 MiB, maxSize=12.6 GiB, persistenceEnabled=false]
[23:03:48] Topology snapshot [ver=15378, servers=1, clients=17, CPUs=24, offheap=13.0GB, heap=22.0GB]
[23:03:48]   ^-- Node [id=D53D63B2-3AD3-47E9-B4CE-3E7B9EB2BB79, clusterState=ACTIVE]
[23:03:48] Data Regions Configured:
[23:03:48]   ^-- default [initSize=256.0 MiB, maxSize=12.6 GiB, persistenceEnabled=false]
[23:03:51] Topology snapshot [ver=15379, servers=2, clients=17, CPUs=32, offheap=25.0GB, heap=23.0GB]
[23:03:51]   ^-- Node [id=D53D63B2-3AD3-47E9-B4CE-3E7B9EB2BB79, clusterState=ACTIVE]
[23:03:51] Data Regions Configured:
[23:03:51]   ^-- default [initSize=256.0 MiB, maxSize=12.6 GiB, persistenceEnabled=false]
[23:04:07] Topology snapshot [ver=15380, servers=2, clients=16, CPUs=32, offheap=25.0GB, heap=23.0GB]
[23:04:07]   ^-- Node [id=D53D63B2-3AD3-47E9-B4CE-3E7B9EB2BB79, clusterState=ACTIVE]
[23:04:07] Data Regions Configured:
[23:04:07]   ^-- default [initSize=256.0 MiB, maxSize=12.6 GiB, persistenceEnabled=false]

[11:59:15,728][SEVERE][tcp-disco-ip-finder-cleaner-#5][TcpDiscoverySpi] Failed to clean IP finder up.
class org.apache.ignite.spi.IgniteSpiException: Failed to retrieve Ignite pods IP addresses.
at org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder.getRegisteredAddresses(TcpDiscoveryKubernetesIpFinder.java:172)
at org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi.registeredAddresses(TcpDiscoverySpi.java:1828)
at org.apache.ignite.spi.discovery.tcp.ServerImpl$IpFinderCleaner.cleanIpFinder(ServerImpl.java:1938)
at org.apache.ignite.spi.discovery.tcp.ServerImpl$IpFinderCleaner.body(ServerImpl.java:1913)
at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:62)
Caused by: java.net.UnknownHostException: kubernetes.default.svc.cluster.local
at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
at java.net.Socket.connect(Socket.java:589)
at sun.security.ssl.SSLSocketImpl.connect(SSLSocketImpl.java:673)
at sun.security.ssl.BaseSSLSocketImpl.connect(BaseSSLSocketImpl.java:173)
at sun.net.NetworkClient.doConnect(NetworkClient.java:180)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:463)
at sun.net.www.http.HttpClient.openServer(HttpClient.java:558)
at sun.net.www.protocol.https.HttpsClient.<init>(HttpsClient.java:264)
at sun.net.www.protocol.https.HttpsClient.New(HttpsClient.java:367)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.getNewHttpClient(AbstractDelegateHttpsURLConnection.java:191)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect0(HttpURLConnection.java:1156)
at sun.net.www.protocol.http.HttpURLConnection.plainConnect(HttpURLConnection.java:1050)
at sun.net.www.protocol.https.AbstractDelegateHttpsURLConnection.connect(AbstractDelegateHttpsURLConnection.java:177)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream0(HttpURLConnection.java:1564)
at sun.net.www.protocol.http.HttpURLConnection.getInputStream(HttpURLConnection.java:1492)
at sun.net.www.protocol.https.HttpsURLConnectionImpl.getInputStream(HttpsURLConnectionImpl.java:263)
at org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder.getRegisteredAddresses(TcpDiscoveryKubernetesIpFinder.java:153)
```

**To Reproduce**
1. execute epicli init ... (with params)
2. edit config file, there should be PostgreSQL and Ignite.
3. execute epicli apply ...  

**OS (please complete the following information):**
 - OS: ???

**Cloud Environment (please complete the following information):**
 - Cloud Provider MS Azure

**Additional context**
Issue based on Jira request: EP-108.

**Comment by rpudlowski93** [comment]
It looks like a problem a little similar to task #1072 and as I remember the problem `Caused by: java.net.UnknownHostException: kubernetes.default.svc.cluster.local` appears when some of DNS pods changed nodes.

**Comment by sk4zuzu** [comment]
@toszo this issue lacks information about which CNI was used to reproduce the problem. If you take a look here http://apache-ignite-users.70518.x6.nabble.com/Ignite-on-RBAC-enabled-K8s-cluster-tp22165p22269.html there is some discussion about similar issue, it does not show the exact solution, but mentions that miscofigured CNI was causing it. We support canal, flannel and calico which one is it ? :hugs:

**Comment by toszo** [comment]
This is request is external - I do not have an information about cni used - I assume flannel (most of usacases is flannel). 
The problem may be related to K8s service discovery used in Ignite. @pyrkamarcin configured Ignite with Zookeeper and it worked without problems.

**Comment by pyrkamarcin** [comment]
@toszo @sk4zuzu I was decided to use ZK for service discovery because K8s as lost connection and lost info about instances. I don't remember exactly the issue, but as @toszo mention, it was some similar.

Ignite discovery config with ZK looks like:
```xml
            <property name="discoverySpi">
              <bean class="org.apache.ignite.spi.discovery.zk.ZookeeperDiscoverySpi">
                <property name="zkConnectionString" value="zk-0.zk-hs.zk.svc.cluster.local,zk-1.zk-hs.zk.svc.cluster.local,zk-2.zk-hs.zk.svc.cluster.local"/>
                <property name="sessionTimeout" value="30000"/>
                <property name="zkRootPath" value="/apacheIgnite"/>
                <property name="joinTimeout" value="10000"/>
              </bean>
            </property>
```
I have tested both cases: in K8s (also ZK) and on VM.

**Comment by mkyc** [comment]
It's still existing issue.

**Comment by atsikham** [comment]
So far I was able to reproduce the error message stated in the description only by scaling coredns deployment down to 0 pods:

```bash
kubectl scale deployment/coredns --replicas=0 -n kube-system
```

This will result to the following Ignite log message in one of the instances that is a "coordinator":

```text
[13:21:20,316][SEVERE][tcp-disco-ip-finder-cleaner-#5-#39][TcpDiscoverySpi] Failed to clean IP finder up.
class org.apache.ignite.spi.IgniteSpiException: Failed to retrieve Ignite pods IP addresses.
        at org.apache.ignite.spi.discovery.tcp.ipfinder.kubernetes.TcpDiscoveryKubernetesIpFinder.getRegisteredAddresses(TcpDiscoveryKubernetesIpFinder.java:170)
        at org.apache.ignite.spi.discovery.tcp.TcpDiscoverySpi.registeredAddresses(TcpDiscoverySpi.java:1965)
        at org.apache.ignite.spi.discovery.tcp.ServerImpl$IpFinderCleaner.cleanIpFinder(ServerImpl.java:2279)
        at org.apache.ignite.spi.discovery.tcp.ServerImpl$IpFinderCleaner.body(ServerImpl.java:2254)
        at org.apache.ignite.spi.IgniteSpiThread.run(IgniteSpiThread.java:58)
Caused by: java.net.UnknownHostException: kubernetes.default.svc.cluster.local
        at java.net.AbstractPlainSocketImpl.connect(AbstractPlainSocketImpl.java:184)
        at java.net.SocksSocketImpl.connect(SocksSocketImpl.java:392)
```

At the same moment control script shows the same information for both pods, cluster is active and the number of nodes is still the same:

```bash
kubectl exec ignite-cluster-5955467bc9-zxgfk -n ignite -- /opt/ignite/apache-ignite/bin/control.sh --state
```

```text
--------------------------------------------------------------------------------
Cluster  ID: 7fe882e6-d189-4fb8-a736-aa8d7ea54a56
Cluster tag: serene_dijkstra
--------------------------------------------------------------------------------
Cluster is active
```

```bash
kubectl exec ignite-cluster-5955467bc9-zxgfk -n ignite -- /opt/ignite/apache-ignite/bin/control.sh --baseline
```

```
Cluster state: active
Current topology version: 2
Baseline auto adjustment enabled: softTimeout=0
Baseline auto-adjust are not scheduled

Current topology version: 2 (Coordinator: ConsistentId=10.244.1.10,127.0.0.1:47500, Order=1)

Baseline nodes:
    ConsistentId=10.244.1.10,127.0.0.1:47500, State=ONLINE, Order=1
    ConsistentId=10.244.1.9,127.0.0.1:47500, State=ONLINE, Order=2
--------------------------------------------------------------------------------
Number of baseline nodes: 2
```

With scaling Ignite instances from 2 to 3 the new pod has the same error message in the log and control script for the new log doesn't respond and it doesn't report anything

```text
kubectl exec ignite-cluster-5955467bc9-v9ssn -n ignite -- /opt/ignite/apache-ignite/bin/control.sh --state   
Control utility [ver. 2.9.1#20201203-sha1:adcce517]
2020 Copyright(C) Apache Software Foundation
User: root
Time: 2021-03-03T13:50:54.514
Command [STATE] started
Arguments: --state
--------------------------------------------------------------------------------
Failed to get cluster state.
Connection to cluster failed. Latest topology update failed.
Command [STATE] finished with code: 2
Control utility has completed execution at: 2021-03-03T13:51:27.857
Execution time: 33343 ms
command terminated with exit code 2
```

At the same time control script for other nodes shows that the third node hasn't joined the cluster.

When coredns is up and running again, the number of cluster nodes immediately becomes 3.

---

Summary
* This particular error message doesn't mean that there is a problem on Ignite side, something can be wrong with networking/DNS for a while, but at the same time Ignite cluster might be healthy.
* From the internal Jira issue description I see other messages happened, such as 

```text
ERROR 1 --- [2%StreamingAPI%] o.a.i.s.d.t.TcpDiscoverySpi : Failed to send message: null java.io.IOException: Failed to get acknowledge for message: TcpDiscoveryClientMetricsUpdateMessage
```

That probably means that one of the nodes [was restarted](http://apache-ignite-developers.2346864.n4.nabble.com/Failed-to-acknowledge-TcpDiscoveryClientMetricsUpdateMessage-td31910.html).

Also there are pod restarts displayed on the provided chart.

* In general this is not a bad case when Ignite node (pod) restarts and re-join as something can happen on the cluster side unless this is a frequent case. Also in the internal issue there are some related memory spikes and they should be investigated, but it seems to be impossible having only provided information.

How I suggest to proceed:
1. Get following information or get an access to the environment where such issue happen, already left the same comment in the related Jira issue:
- Is it HA cluster or not (single or multiple K8s control plain nodes)?
- Which Epiphany version was used to deploy the cluster?
- Which K8s version?
- Which OS is used in cluster setup - RedHat or Ubuntu?
- Which CNI is used - flannel/calico/canal?
- Does it happen if [recent changes](https://github.com/epiphany-platform/epiphany/tree/develop/tools/development/k8s/memory/patch_cgroup_driver) to cgroups driver applied?
- Does it happen if amount of resources per pod increased?
- If there is a cluster with a single control plane mode, does switching to HA help?

2. Investigate this issue further. Apply [cgroups driver patch](https://github.com/epiphany-platform/epiphany/tree/develop/tools/development/k8s/memory/patch_cgroup_driver). Configure resource quotas.

3. About applying Zookeeper discovery: we should be able to reproduce this issue first to know if that helps or not or try to use configuration provided by @pyrkamarcin. If we decide just to switch to the discovery by Zookeeper, we need to implement Zookeeper deployment in K8s, but it doesn't guarantee that the issue will be solved.

Configuration that was used for test:
```yaml
---
kind: configuration/applications
title: "Kubernetes Applications Config"
provider: azure
name: default
specification:
  applications:
  - name: ignite-stateless
    enabled: yes
    image_path: "apacheignite/ignite:2.9.1" # it will be part of the image path: {{local_repository}}/{{image_path}}
    namespace: ignite
    service:
      rest_nodeport: 32300
      sql_nodeport: 32301
      thinclients_nodeport: 32302
    replicas: 2
    enabled_plugins:
    - ignite-kubernetes # required to work on K8s
    - ignite-rest-http
```

**Comment by atsikham** [comment]
Update:

I figured out that it's not possible to configure Ignite deployment resource quotas via epicli and probably they are not configured in the cluster where this issue happens. Requested configuring deployment's resource quotas as it may lead to frequent pod restarts.

---
K8s cluster configuration where the issue occurs:

* Is it HA cluster or not (single or multiple K8s control plain nodes)?
_For the Dev10 cluster it was set up with a single master node_

* Which Epiphany version was used to deploy the cluster?
_I’m not sure, but might be 0.6?  Is there an easy way to tell?_

* Which K8s version?
_kubectl version shows 1.17.4_

* Which OS is used in cluster setup - RedHat or Ubuntu?
_Ubuntu 18.04_

* Which CNI is used - flannel/calico/canal?
_I think it may be flannel, but not sure_

**Comment by rafzei** [comment]
@atsikham Could you please create a new gh issue to implement such functionality?
