### ISSUE TITLE
[BUG] Error running upgrade on a 0.3 cluster: missing shared-config

### ISSUE THREAD

**Issue by przemyslavic** [epiphany-platform/epiphany#1491]
**Describe the bug**
When trying to upgrade a 0.3 cluster to develop, the user should receive a message that this type of upgrade is not supported (according to PR https://github.com/epiphany-platform/epiphany/pull/1476). In fact epiphany throws an error right after running the command `epicli upgrade` because of missing shared-config in the manifest file.

**To Reproduce**
1. Deploy a 0.3 cluster using image `epiphanyplatform/epicli:0.3.1`
2. Execute `epicli upgrade -b /path/to/build/dir` from develop branch

**Expected behavior**
The upgrade aborts with the message `Your Kubernetes version ({{ cluster_version }}) is not supported by this version of Epiphany which requires at least version 1.14.6 (Epiphany v0.4.4). For more information, refer to the documentation.` because the assertion was not satisfied.

**Actual behavior**
Epicli fails with `ERROR epicli - Expected one element but received: 0`

**OS (please complete the following information):**
 - OS: [all]

**Cloud Environment (please complete the following information):**
 - Cloud Provider [all]

**Additional context**
Debug log:
```
13:16:28 ERROR epicli - Expected one element but received: 0
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cli/epicli.py", line 127, in main
    return args.func(args)
  File "/usr/local/lib/python3.7/site-packages/cli/epicli.py", line 227, in run_upgrade
    return engine.upgrade()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/UpgradeEngine.py", line 54, in upgrade
    ansible_runner.upgrade()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/ansible/AnsibleRunner.py", line 137, in upgrade
    ansible_vars_generator.generate()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/ansible/AnsibleVarsGenerator.py", line 74, in generate
    self.populate_group_vars(ansible_dir)
  File "/usr/local/lib/python3.7/site-packages/cli/engine/ansible/AnsibleVarsGenerator.py", line 99, in populate_group_vars
    shared_config_doc = self.get_shared_config_from_manifest()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/ansible/AnsibleVarsGenerator.py", line 149, in get_shared_config_from_manifest
    shared_config_doc = select_single(manifest_docs, lambda x: x.kind == 'configuration/shared-config')
  File "/usr/local/lib/python3.7/site-packages/cli/helpers/doc_list_helpers.py", line 31, in select_single
    raise ExpectedSingleResultException("Expected one element but received: " + str(elements_count))
cli.helpers.doc_list_helpers.ExpectedSingleResultException: Expected one element but received: 0
```

**Comment by mkyc** [comment]
@toszo can you get information if we know about any 0.3 cluster existing out there in the wild?

**Comment by mkyc** [comment]
@przemyslavic there are such clusters.

**Comment by przemyslavic** [comment]
The fix has been tested. The error described above no longer occurs.
