### ISSUE TITLE
Python error while running script to download files for air gapped installation

### ISSUE THREAD

**Issue by rahulrajanrepo** [epiphany-platform/epiphany#3329]
Hi Team, I'm getting below error while running python script for downloading files for air gapped installation,

Steps followed-
1. epicli prepare --os ubuntu-20.04 --arch x86_64
2. cd build/prepare_scripts_ubuntu_2004_x86_64/
3. sudo python3 download-requirements.py /requirementsoutput/ ubuntu-20.04

Error - IndexError: list index out of range

![error](https://user-images.githubusercontent.com/49981814/224935268-0f44e44d-0776-4fbe-9b4c-e21392ccc0f0.PNG)

**Comment by sbbroot** [comment]
Hello,

We would need more information, please rerun the script with the debug flag:
```
sudo python3 download-requirements.py /requirementsoutput/ ubuntu-20.04 --log-level=debug
```
Post the output here.

Also, did you change/add something to `requirements/x86_64/debian/ubuntu-20.04/packages.yml` file?

Thanks.

**Comment by rahulrajanrepo** [comment]
Thanks for the response, I did not make any changes to the mentioned file.

Please find the logs attached with debug
[error.txt.txt](https://github.com/epiphany-platform/epiphany/files/10966446/error.txt.txt)

**Comment by rahulrajanrepo** [comment]
epiuser@rahul-VirtualBox:/shared/build/prepare_scripts_ubuntu_2004_x86_64$ sudo python3 download-requirements.py /requirementsoutput/ ubuntu-20.04 --log-level=debug
2023-03-14 09:00:03,469 [DEBUG]: Found Matching OS: `Ubuntu`
2023-03-14 09:00:03,469 [INFO]: Info summary:
--------------------------------------------------
OS Arch: x86_64
OS Type: ubuntu-20.04
Script location: /shared/build/prepare_scripts_ubuntu_2004_x86_64
Directories used:
- files:              /requirementsoutput/files
- grafana dashboards: /requirementsoutput/grafana_dashboards
- images:             /requirementsoutput/images
- packages:           /requirementsoutput/packages
Repos backup file: /var/tmp/enabled-system-repos.tar
Manifest not used, downloading all available requirements...
Log file location: /shared/build/prepare_scripts_ubuntu_2004_x86_64/download-requirements.log
Verbose mode: True
Retries count: 3
--------------------------------------------------
2023-03-14 09:00:03,510 [INFO]: 
Files to download:
- alertmanager
- apache-zookeeper
- filebeat-chart
- helm
- jmx-prometheus-javaagent
- kafka
- kafka-exporter
- keycloak
- node-exporter
- node-exporter-chart
- opensearch
- opensearch-dashboards
- opensearch-perf-top
- postgres-exporter
- prometheus
- rook-ceph-chart
- rook-ceph-cluster-chart

Dashboards to download:
- grafana_dashboard_10991
- grafana_dashboard_11074
- grafana_dashboard_179
- grafana_dashboard_1860
- grafana_dashboard_315
- grafana_dashboard_405
- grafana_dashboard_4279
- grafana_dashboard_455
- grafana_dashboard_6663
- grafana_dashboard_7249
- grafana_dashboard_7589
- grafana_dashboard_789
- grafana_dashboard_9628

Images to download:
- bitnami/pgbouncer:1.16.0
- bitnami/pgpool:4.2.4
- calico/cni:v3.15.0
- calico/cni:v3.20.3
- calico/cni:v3.23.3
- calico/kube-controllers:v3.15.0
- calico/kube-controllers:v3.20.3
- calico/kube-controllers:v3.23.3
- calico/node:v3.15.0
- calico/node:v3.20.3
- calico/node:v3.23.3
- calico/pod2daemon-flexvol:v3.15.0
- calico/pod2daemon-flexvol:v3.20.3
- docker.io/busybox:1.32
- haproxy:2.2.2-alpine
- k8s.gcr.io/coredns/coredns:v1.8.0
- k8s.gcr.io/coredns/coredns:v1.8.4
- k8s.gcr.io/coredns:1.6.7
- k8s.gcr.io/coredns:1.7.0
- k8s.gcr.io/etcd:3.4.13-0
- k8s.gcr.io/etcd:3.4.3-0
- k8s.gcr.io/etcd:3.5.0-0
- k8s.gcr.io/kube-apiserver:v1.18.6
- k8s.gcr.io/kube-apiserver:v1.19.15
- k8s.gcr.io/kube-apiserver:v1.20.12
- k8s.gcr.io/kube-apiserver:v1.21.7
- k8s.gcr.io/kube-apiserver:v1.22.4
- k8s.gcr.io/kube-controller-manager:v1.18.6
- k8s.gcr.io/kube-controller-manager:v1.19.15
- k8s.gcr.io/kube-controller-manager:v1.20.12
- k8s.gcr.io/kube-controller-manager:v1.21.7
- k8s.gcr.io/kube-controller-manager:v1.22.4
- k8s.gcr.io/kube-proxy:v1.18.6
- k8s.gcr.io/kube-proxy:v1.19.15
- k8s.gcr.io/kube-proxy:v1.20.12
- k8s.gcr.io/kube-proxy:v1.21.7
- k8s.gcr.io/kube-proxy:v1.22.4
- k8s.gcr.io/kube-scheduler:v1.18.6
- k8s.gcr.io/kube-scheduler:v1.19.15
- k8s.gcr.io/kube-scheduler:v1.20.12
- k8s.gcr.io/kube-scheduler:v1.21.7
- k8s.gcr.io/kube-scheduler:v1.22.4
- k8s.gcr.io/pause:3.2
- k8s.gcr.io/pause:3.4.1
- k8s.gcr.io/pause:3.5
- k8s.gcr.io/sig-storage/csi-attacher:v3.4.0
- k8s.gcr.io/sig-storage/csi-node-driver-registrar:v2.5.0
- k8s.gcr.io/sig-storage/csi-provisioner:v3.1.0
- k8s.gcr.io/sig-storage/csi-resizer:v1.4.0
- k8s.gcr.io/sig-storage/csi-snapshotter:v5.0.1
- kubernetesui/dashboard:v2.3.1
- kubernetesui/metrics-scraper:v1.0.7
- quay.io/ceph/ceph:v16.2.7-20220510
- quay.io/cephcsi/cephcsi:v3.5.1
- quay.io/coreos/flannel:v0.12.0
- quay.io/coreos/flannel:v0.12.0-amd64
- quay.io/coreos/flannel:v0.14.0
- quay.io/coreos/flannel:v0.14.0-amd64
- quay.io/coreos/flannel:v0.15.1
- quay.io/csiaddons/k8s-sidecar:v0.2.1
- quay.io/csiaddons/volumereplication-operator:v0.3.0
- quay.io/keycloak/keycloak:19.0.2
- rabbitmq:3.8.9
- registry:2.8.0
- rook/ceph:v1.8.8

2023-03-14 09:00:03,510 [INFO]: Installing base packages...
2023-03-14 09:00:03,510 [DEBUG]: [1/3] Running: `apt list --installed`
2023-03-14 09:00:04,014 [DEBUG]: [1/3] Running: `apt install -y ca-certificates`
2023-03-14 09:00:04,579 [INFO]: Done installing base packages.
2023-03-14 09:00:04,579 [INFO]: Restoring repository files...
2023-03-14 09:00:04,579 [DEBUG]: Removing files from /etc/apt/sources.list.d...
2023-03-14 09:00:04,580 [DEBUG]: - 2ndquadrant-dl-default-release.list
2023-03-14 09:00:04,580 [DEBUG]: - rabbitmq.list
2023-03-14 09:00:04,580 [DEBUG]: - docker-ce.list
2023-03-14 09:00:04,580 [DEBUG]: - pgdg.list
2023-03-14 09:00:04,580 [DEBUG]: - elastic-6.x.list
2023-03-14 09:00:04,580 [DEBUG]: - erlang-23.x.list
2023-03-14 09:00:04,580 [DEBUG]: - kubernetes.list
2023-03-14 09:00:04,580 [DEBUG]: - pgdg-archive.list
2023-03-14 09:00:04,580 [DEBUG]: - elastic-7.x.list
2023-03-14 09:00:04,580 [DEBUG]: Done removing files.
2023-03-14 09:00:04,580 [DEBUG]: [1/1] Running: `tar -xvf /var/tmp/enabled-system-repos.tar --absolute-names --directory / --overwrite`
2023-03-14 09:00:04,582 [INFO]: Done restoring repository files.
2023-03-14 09:00:04,582 [INFO]: Adding third party repositories...
2023-03-14 09:00:04,582 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/elastic-6.x --prefer-family=IPv4 https://artifacts.elastic.co/GPG-KEY-elasticsearch`
2023-03-14 09:00:04,775 [DEBUG]: [1/3] Running: `apt-key add /tmp/elastic-6.x`
2023-03-14 09:00:05,054 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/kubernetes --prefer-family=IPv4 https://packages.cloud.google.com/apt/doc/apt-key.gpg`
2023-03-14 09:00:05,466 [DEBUG]: [1/3] Running: `apt-key add /tmp/kubernetes`
2023-03-14 09:00:05,744 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/erlang-23.x --prefer-family=IPv4 https://packages.erlang-solutions.com/ubuntu/erlang_solutions.asc`
2023-03-14 09:00:06,567 [DEBUG]: [1/3] Running: `apt-key add /tmp/erlang-23.x`
2023-03-14 09:00:06,860 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/rabbitmq --prefer-family=IPv4 https://packagecloud.io/rabbitmq/rabbitmq-server/gpgkey`
2023-03-14 09:00:08,008 [DEBUG]: [1/3] Running: `apt-key add /tmp/rabbitmq`
2023-03-14 09:00:08,287 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/docker-ce --prefer-family=IPv4 https://download.docker.com/linux/ubuntu/gpg`
2023-03-14 09:00:08,427 [DEBUG]: [1/3] Running: `apt-key add /tmp/docker-ce`
2023-03-14 09:00:08,701 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/elastic-7.x --prefer-family=IPv4 https://artifacts.elastic.co/GPG-KEY-elasticsearch`
2023-03-14 09:00:08,847 [DEBUG]: [1/3] Running: `apt-key add /tmp/elastic-7.x`
2023-03-14 09:00:09,122 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/pgdg --prefer-family=IPv4 https://www.postgresql.org/media/keys/ACCC4CF8.asc`
2023-03-14 09:00:10,261 [DEBUG]: [1/3] Running: `apt-key add /tmp/pgdg`
2023-03-14 09:00:10,542 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/pgdg-archive --prefer-family=IPv4 https://www.postgresql.org/media/keys/ACCC4CF8.asc`
2023-03-14 09:00:11,758 [DEBUG]: [1/3] Running: `apt-key add /tmp/pgdg-archive`
2023-03-14 09:00:12,042 [DEBUG]: [1/3] Running: `wget --no-use-server-timestamps --show-progress --output-document=/tmp/2ndquadrant-dl-default-release --prefer-family=IPv4 https://dl.2ndquadrant.com/gpg-key.asc`
2023-03-14 09:00:13,107 [DEBUG]: [1/3] Running: `apt-key add /tmp/2ndquadrant-dl-default-release`
2023-03-14 09:00:13,385 [DEBUG]: [1/3] Running: `apt update`
2023-03-14 09:00:25,761 [INFO]: Done adding third party repositories.
2023-03-14 09:00:25,761 [INFO]: Downloading packages from repos...
2023-03-14 09:00:25,761 [DEBUG]: [1/3] Running: `apt-cache show adduser`
2023-03-14 09:00:26,126 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends adduser=3.118`
2023-03-14 09:00:26,633 [DEBUG]: [1/3] Running: `apt-cache show apt-transport-https`
2023-03-14 09:00:27,008 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends apt-transport-https=2.2.4`
2023-03-14 09:00:27,474 [DEBUG]: [1/3] Running: `apt-cache show auditd`
2023-03-14 09:00:27,857 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends auditd=1:3.0-2`
2023-03-14 09:00:28,316 [DEBUG]: [1/3] Running: `apt-cache show bash-completion`
2023-03-14 09:00:28,686 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends bash-completion=1:2.11-2`
2023-03-14 09:00:29,151 [DEBUG]: [1/3] Running: `apt-cache show ca-certificates`
2023-03-14 09:00:29,524 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends ca-certificates=20210119`
2023-03-14 09:00:29,987 [DEBUG]: [1/3] Running: `apt-cache show cifs-utils`
2023-03-14 09:00:30,361 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends cifs-utils=2:6.11-3.1+deb11u1`
2023-03-14 09:00:30,835 [DEBUG]: [1/3] Running: `apt-cache show containerd.io=1.5.11*`
2023-03-14 09:00:31,202 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends containerd.io=1.5.11-1`
2023-03-14 09:00:31,653 [DEBUG]: [1/3] Running: `apt-cache show cri-tools=1.25.0*`
2023-03-14 09:00:32,037 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends cri-tools=1.25.0-00`
2023-03-14 09:00:32,510 [DEBUG]: [1/3] Running: `apt-cache show curl`
2023-03-14 09:00:32,887 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends curl=7.74.0-1.3+deb11u7`
2023-03-14 09:00:33,353 [DEBUG]: [1/3] Running: `apt-cache show docker-ce=5:20.10.8*`
2023-03-14 09:00:33,746 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends docker-ce=5:20.10.8~3-0~ubuntu-focal`
2023-03-14 09:00:34,243 [DEBUG]: [1/3] Running: `apt-cache show docker-ce-cli=5:20.10.8*`
2023-03-14 09:00:34,615 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends docker-ce-cli=5:20.10.8~3-0~ubuntu-focal`
2023-03-14 09:00:35,089 [DEBUG]: [1/3] Running: `apt-cache show docker-ce-rootless-extras=5:20.10.8*`
2023-03-14 09:00:35,462 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends docker-ce-rootless-extras=5:20.10.8~3-0~ubuntu-focal`
2023-03-14 09:00:35,921 [DEBUG]: [1/3] Running: `apt-cache show ebtables`
2023-03-14 09:00:36,303 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends ebtables=2.0.11-4+b1`
2023-03-14 09:00:36,766 [DEBUG]: [1/3] Running: `apt-cache show elasticsearch-oss=7.10.2*`
2023-03-14 09:00:37,175 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends elasticsearch-oss=7.10.2`
2023-03-14 09:00:37,631 [DEBUG]: [1/3] Running: `apt-cache show erlang-asn1=1:23.1.5*`
2023-03-14 09:00:38,014 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-asn1=1:23.1.5-1`
2023-03-14 09:00:38,491 [DEBUG]: [1/3] Running: `apt-cache show erlang-base=1:23.1.5*`
2023-03-14 09:00:38,865 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-base=1:23.1.5-1`
2023-03-14 09:00:39,329 [DEBUG]: [1/3] Running: `apt-cache show erlang-crypto=1:23.1.5*`
2023-03-14 09:00:39,711 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-crypto=1:23.1.5-1`
2023-03-14 09:00:40,183 [DEBUG]: [1/3] Running: `apt-cache show erlang-eldap=1:23.1.5*`
2023-03-14 09:00:40,559 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-eldap=1:23.1.5-1`
2023-03-14 09:00:41,037 [DEBUG]: [1/3] Running: `apt-cache show erlang-ftp=1:23.1.5*`
2023-03-14 09:00:41,416 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-ftp=1:23.1.5-1`
2023-03-14 09:00:41,924 [DEBUG]: [1/3] Running: `apt-cache show erlang-inets=1:23.1.5*`
2023-03-14 09:00:42,340 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-inets=1:23.1.5-1`
2023-03-14 09:00:42,879 [DEBUG]: [1/3] Running: `apt-cache show erlang-mnesia=1:23.1.5*`
2023-03-14 09:00:43,262 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-mnesia=1:23.1.5-1`
2023-03-14 09:00:43,764 [DEBUG]: [1/3] Running: `apt-cache show erlang-os-mon=1:23.1.5*`
2023-03-14 09:00:44,146 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-os-mon=1:23.1.5-1`
2023-03-14 09:00:44,631 [DEBUG]: [1/3] Running: `apt-cache show erlang-parsetools=1:23.1.5*`
2023-03-14 09:00:45,004 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-parsetools=1:23.1.5-1`
2023-03-14 09:00:45,500 [DEBUG]: [1/3] Running: `apt-cache show erlang-public-key=1:23.1.5*`
2023-03-14 09:00:45,880 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-public-key=1:23.1.5-1`
2023-03-14 09:00:46,358 [DEBUG]: [1/3] Running: `apt-cache show erlang-runtime-tools=1:23.1.5*`
2023-03-14 09:00:46,752 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-runtime-tools=1:23.1.5-1`
2023-03-14 09:00:47,235 [DEBUG]: [1/3] Running: `apt-cache show erlang-snmp=1:23.1.5*`
2023-03-14 09:00:47,610 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-snmp=1:23.1.5-1`
2023-03-14 09:00:48,107 [DEBUG]: [1/3] Running: `apt-cache show erlang-ssl=1:23.1.5*`
2023-03-14 09:00:48,508 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-ssl=1:23.1.5-1`
2023-03-14 09:00:48,988 [DEBUG]: [1/3] Running: `apt-cache show erlang-syntax-tools=1:23.1.5*`
2023-03-14 09:00:49,365 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-syntax-tools=1:23.1.5-1`
2023-03-14 09:00:49,866 [DEBUG]: [1/3] Running: `apt-cache show erlang-tftp=1:23.1.5*`
2023-03-14 09:00:50,248 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-tftp=1:23.1.5-1`
2023-03-14 09:00:50,725 [DEBUG]: [1/3] Running: `apt-cache show erlang-tools=1:23.1.5*`
2023-03-14 09:00:51,100 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-tools=1:23.1.5-1`
2023-03-14 09:00:51,570 [DEBUG]: [1/3] Running: `apt-cache show erlang-xmerl=1:23.1.5*`
2023-03-14 09:00:51,955 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends erlang-xmerl=1:23.1.5-1`
2023-03-14 09:00:52,415 [DEBUG]: [1/3] Running: `apt-cache show ethtool`
2023-03-14 09:00:52,791 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends ethtool=1:5.9-1`
2023-03-14 09:00:53,255 [DEBUG]: [1/3] Running: `apt-cache show filebeat=7.12.1*`
2023-03-14 09:00:53,631 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends filebeat=7.12.1`
2023-03-14 09:00:54,095 [DEBUG]: [1/3] Running: `apt-cache show firewalld`
2023-03-14 09:00:54,491 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends firewalld=0.9.3-2`
2023-03-14 09:00:54,958 [DEBUG]: [1/3] Running: `apt-cache show fping`
2023-03-14 09:00:55,330 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends fping=5.0-1`
2023-03-14 09:00:55,831 [DEBUG]: [1/3] Running: `apt-cache show gnupg2`
2023-03-14 09:00:56,254 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends gnupg2=2.2.27-2+deb11u2`
2023-03-14 09:00:56,727 [DEBUG]: [1/3] Running: `apt-cache show htop`
2023-03-14 09:00:57,121 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends htop=3.0.5-7`
2023-03-14 09:00:57,615 [DEBUG]: [1/3] Running: `apt-cache show iftop`
2023-03-14 09:00:58,002 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends iftop=1.0~pre4-7`
2023-03-14 09:00:58,469 [DEBUG]: [1/3] Running: `apt-cache show jq`
2023-03-14 09:00:58,854 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends jq=1.6-2.1`
2023-03-14 09:00:59,327 [DEBUG]: [1/3] Running: `apt-cache show libdpkg-perl`
2023-03-14 09:00:59,700 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends libdpkg-perl=1.20.12`
2023-03-14 09:01:00,169 [DEBUG]: [1/3] Running: `apt-cache show libfontconfig1`
2023-03-14 09:01:00,574 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends libfontconfig1=2.13.1-4.2`
2023-03-14 09:01:01,080 [DEBUG]: [1/3] Running: `apt-cache show logrotate`
2023-03-14 09:01:01,485 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends logrotate=3.18.0-2+deb11u1`
2023-03-14 09:01:01,960 [DEBUG]: [1/3] Running: `apt-cache show netcat`
2023-03-14 09:01:02,347 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends netcat=1.10-46`
2023-03-14 09:01:02,830 [DEBUG]: [1/3] Running: `apt-cache show net-tools`
2023-03-14 09:01:03,221 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends net-tools=1.60+git20181103.0eebece-1`
2023-03-14 09:01:03,720 [DEBUG]: [1/3] Running: `apt-cache show nfs-common`
2023-03-14 09:01:04,113 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends nfs-common=1:1.3.4-6`
2023-03-14 09:01:04,603 [DEBUG]: [1/3] Running: `apt-cache show libtirpc3`
2023-03-14 09:01:04,983 [DEBUG]: [1/3] Running: `apt-cache depends --no-recommends --no-suggests --no-conflicts --no-breaks --no-replaces --no-enhances --no-pre-depends libtirpc3=1.3.1-1+deb11u1`
2023-03-14 09:01:05,466 [DEBUG]: [1/3] Running: `apt-cache show openjdk-8-jre-headless`
Traceback (most recent call last):
  File "/shared/build/prepare_scripts_ubuntu_2004_x86_64/download-requirements.py", line 92, in <module>
    sys.exit(main(sys.argv))
  File "/shared/build/prepare_scripts_ubuntu_2004_x86_64/download-requirements.py", line 72, in main
    run(config)
  File "/shared/build/prepare_scripts_ubuntu_2004_x86_64/src/run.py", line 19, in run
    MODES[config.os_type](config).run()
  File "/shared/build/prepare_scripts_ubuntu_2004_x86_64/src/mode/base_mode.py", line 318, in run
    self._download_packages()
  File "/shared/build/prepare_scripts_ubuntu_2004_x86_64/src/mode/debian_family_mode.py", line 88, in _download_packages
    package_info = self._tools.apt_cache.get_package_info(package_base_name, version)
  File "/shared/build/prepare_scripts_ubuntu_2004_x86_64/src/command/debian/apt_cache.py", line 26, in get_package_info
    version_info: str = [item for item in show_output.split('\n\n') if 'Version' in item][0]
IndexError: list index out of range
epiuser@rahul-VirtualBox:/shared/build/prepare_scripts_ubuntu_2004_x86_64$

**Comment by rahulrajanrepo** [comment]
Hi Team, 

would you kindly give me an update, I'm working on a production deployment

Thanks

**Comment by sbbroot** [comment]
Could you run this command?

`apt-cache show openjdk-8-jre-headless`

I would like to see the output.

Have you changed/added something in system's repositories?

Thanks

**Comment by seriva** [comment]
@rahulrajanpondy We are not seeing this issues in our build environments and both me and @sbbroot also ran this the Ubuntu-20.04 requirements locally without any issues.

**Comment by rahulrajanrepo** [comment]
Hi @seriva @sbbroot, 

I replicated the same steps in my another ubuntu machine, looks like I'm getting the same error.
I did not modify any of the configuration files, all are default.
Given below the details of my setup and epiphany version I'm trying to run,
Ubunutu version - 20.04
Epiphany version - 2.0.4
Output of command (apt-cache show openjdk-8-jre-headless) -
epiuser@azureagent:/shared/build/prepare_scripts_ubuntu_2004_x86_64$ sudo apt-cache show openjdk-8-jre-headless
N: Can't select versions from package 'openjdk-8-jre-headless' as it is purely virtual
N: No packages found

Thanks!

**Comment by sbbroot** [comment]
This is a regular Ubuntu package, it should be there.
Can You check `/etc/apt/sources.list` and see if everything is ok there?

Thanks!

**Comment by rahulrajanrepo** [comment]
Hi @sbbroot,

Please find the details below

![image](https://user-images.githubusercontent.com/49981814/225281242-9bcdcc36-20b5-4eeb-85e7-c88d2ed302d0.png)

Thanks

**Comment by przemyslavic** [comment]
@rahulrajanpondy 
You are running Debian 11 bullseye and not Ubuntu 20.04 (or you have repositories set up like that).
The script should be run on Ubuntu 20.04 vm/container and not in the epicli container.

**Comment by rahulrajanrepo** [comment]
Hi @przemyslavic , looks like this is the cause of the issue, now script is executing as expected.. Thanks
