### ISSUE TITLE
Getting started with Epiphany

### ISSUE THREAD

**Issue by samiralajmovic** [epiphany-platform/epiphany#508]
Hey, I'm working with ABB (the AVT department), and we're looking to migrate our infrastructure to use Epiphany.
Our services will need to be able to run both in the Cloud (Azure most likely) and locally, which you support so that's great!
However, I stumbled upon some issues and was wondering if you have any idea what could be wrong?

1. I could't get the Docker image epicli 0.3.0 to work, the commands and error output is:
 ```
  $ docker pull epiphanyplatform/epicli:0.3.0

  # I'm in a directory with a data.yaml file
  $ docker run -it -v $PWD:/shared --rm epiphanyplatform/epicli:0.3.0 epicli --version

  /usr/local/bin/epicli: line 3: import: command not found
  /usr/local/bin/epicli: line 4: import: command not found
  /usr/local/bin/epicli: line 6: from: command not found
  /usr/local/bin/epicli: epicli: line 9: syntax error near unexpected token `('
  /usr/local/bin/epicli: epicli: line 9: `    sys.argv[0] = re.sub(r'(-script\.pyw?|\.exe)?$', '', sys.argv[0])'
 ```

2. When I install `epicli` locally, I manage to run `epicli --version` and get the correct output, 0.3.0. But when I run the following commands I get an error:
 ```
  # Tried with platform aws and any
  $ (epicli) samir@ ~/projects/avt/epiphany/core (master) $ epicli init -p any -n demo
    13:29:42 INFO config - docker_cli = False
    13:29:42 INFO config - output_dir = '/home/samir/projects/avt/epiphany/core'
    13:29:42 INFO config - log_file = 'log.log'
    13:29:42 INFO config - log_format = '%(asctime)s %(levelname)s %(name)s - %(message)s'
    13:29:42 INFO config - log_date_format = '%H:%M:%S'
    13:29:42 INFO config - log_count = 10
    13:29:42 INFO config - log_type = 'plain'
    13:29:42 INFO config - validate_certs = True
    13:29:42 INFO config - debug = False
    13:29:42 INFO config - auto_approve = False
    13:29:42 INFO cli.engine.InitEngine - Starting run
    13:29:42 INFO cli.engine.InitEngine - Run done in 0ms
    13:29:42 ERROR epicli - [Errno 2] No such file or directory: '/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/helpers/../../data/common/defaults/configuration/minimal-cluster-config.yml'

  # Also get  13:39:36 ERROR epicli - No such attribute: provider when running
  $ epicli apply -f data.yaml
 # I'm using epiphany/core/data/metal/epiphany-single-machine/data.yaml as config file
 ```
Do you reckon there is some issue with my python 3.7 setup?

3. Is there any support for Windows images since one of our services uses [Microsoft Windows Server Core ltsc2019](https://hub.docker.com/_/microsoft-windows-servercore). All of our Docker images will use as a Ubuntu base image, except one which might need to run a Windows image on one of the Kubernetes nodes, unfortunately :(

My setup is:
- Ubuntu 18.04
- Latest epiphany release 0.3.0, working from master branch (I tried development branch as well)
- Python 3.7
- Bare metal, haven't installed VirtualBox

**Comment by seriva** [comment]
Hey!

To awser your questions:

1: Try to run the Epicli container without the "epicli --version" command behind. It should open the bash prompt from inside the container starting from the shared folder from where you can execute epicli commands.

2: How did you setup the virtualenv to install the epicli wheel?

3: We currently dont support Windows nodes. From what I remember its on the roadmap but not for the foreseeable feature.

Cheers
Luuk

**Comment by samiralajmovic** [comment]
Cheers for the quick reply!

1. Ah my bad. Command now works, but I get the following output when running `epicli verify -f data.yaml`, from directory `epiphany/core/data/metal/epiphany-single-machine`.
```
17:38:46 INFO config - docker_cli = True
17:38:46 INFO config - output_dir = '/shared/'
17:38:46 INFO config - log_file = 'log.log'
17:38:46 INFO config - log_format = '%(asctime)s %(levelname)s %(name)s - %(message)s'
17:38:46 INFO config - log_date_format = '%H:%M:%S'
17:38:46 INFO config - log_count = 10
17:38:46 INFO config - log_type = 'plain'
17:38:46 INFO config - validate_certs = True
17:38:46 INFO cli.engine.DefaultMerger - Starting run
17:38:46 INFO cli.engine.DefaultMerger - Run done in 0ms
17:38:46 ERROR cli.engine.EpiphanyEngine - No such attribute: provider
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 81, in verify
    self.process_input_docs()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 44, in process_input_do
    self.input_docs = doc_merger.run()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/DefaultMerger.py", line 16, in run
    files_with_defaults = load_all_yaml_objs(types.DEFAULT, doc.provider, doc.kind)
  File "/usr/local/lib/python3.7/site-packages/cli/helpers/ObjDict.py", line 6, in __getattr__
    raise AttributeError("No such attribute: " + name)
AttributeError: No such attribute: provider
```

So I specified provider to metal:

```
kind: datafile
version: 0.3.0
provider: metal
```

but now i get the following error:
```
17:50:04 INFO config - docker_cli = True
17:50:04 INFO config - output_dir = '/shared/'
17:50:04 INFO config - log_file = 'log.log'
17:50:04 INFO config - log_format = '%(asctime)s %(levelname)s %(name)s - %(message)s'
17:50:04 INFO config - log_date_format = '%H:%M:%S'
17:50:04 INFO config - log_count = 10
17:50:04 INFO config - log_type = 'plain'
17:50:04 INFO config - validate_certs = True
17:50:04 INFO cli.engine.DefaultMerger - Starting run
17:50:04 INFO cli.engine.DefaultMerger - Run done in 0ms
17:50:04 ERROR cli.engine.EpiphanyEngine - [Errno 2] No such file or directory: '/usr/local/epicli/data/common/defaults/datafile.yml'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 96, in apply
    self.process_input_docs()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 44, in process_input_docs
    self.input_docs = doc_merger.run()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/DefaultMerger.py", line 16, in run
    files_with_defaults = load_all_yaml_objs(types.DEFAULT, doc.provider, doc.kind)
  File "/usr/local/lib/python3.7/site-packages/cli/helpers/data_loader.py", line 43, in load_all_yaml_objs
    return load_file_from_path(script_dir, path_to_file, file_type, kind)
  File "/usr/local/lib/python3.7/site-packages/cli/helpers/data_loader.py", line 52, in load_file_from_path
    with open(path_to_file, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/epicli/data/common/defaults/datafile.yml'
```

Running from the docker image. Are there more steps that I need to complete before deploying locally to my computer (preferably virtualbox, but there isn't any example of a virtualbox config file in `core/data/vbox`?

2: How did you setup the virtualenv to install the epicli wheel?
I followed the instructions on the how to guide. I can debug more here and see if there's something wrong with my Python setup, but the docker image should suffice.

**Comment by seriva** [comment]
Hey man,

For 1:

The yaml that you are trying to run is for the the legacy epiphany which we will drop by the end of the year. We still need to update the documentation in a few places for the Epicli CLI stuff. For  Epicli you should be able to use this yaml for a single machine installation:

`kind: epiphany-cluster
version: 0.3.0
title: "Epiphany cluster Config"
provider: any
name: "default"
specification:
  name: YOUR_CLUSTER_NAME
  admin_user:
    name: operations # YOUR-ADMIN-USERNAME
    key_path: /user/.ssh/epiphany-operations/id_rsa # YOUR-SSH-KEY-PATH
  components:
    single_machine:
      count: 1
      machines:
        - single-machine
---
kind: infrastructure/machine
provider: any
name: single-machine
specification:
  hostname: master    # YOUR-MACHINE-HOSTNAME
  ip: 192.168.100.101 # YOUR-MACHINE-IP`

The single_machine: component will install the following roles on the specified machine:

      - kubernetes-master
      - rabbitmql
      - postgresql

Any other roles like monitoring, logging etc are kind of useless on a single machine cluster. In the  single-machine you need to update the IP and Hostname to point to you VM or physical machine ofcourse.

Then make sure the Epicli docker and the VM/Machine are on the same network and run:

epicli apply -f data.yaml

Cheer
Luuk

**Comment by samiralajmovic** [comment]
1. I got this from running the yaml config file you provided:
```
bash-5.0# epicli apply -f test.yaml
07:33:10 INFO config - docker_cli = True
07:33:10 INFO config - output_dir = '/shared/'
07:33:10 INFO config - log_file = 'log.log'
07:33:10 INFO config - log_format = '%(asctime)s %(levelname)s %(name)s - %(message)s'
07:33:10 INFO config - log_date_format = '%H:%M:%S'
07:33:10 INFO config - log_count = 10
07:33:10 INFO config - log_type = 'plain'
07:33:10 INFO config - validate_certs = True
07:33:10 INFO cli.engine.DefaultMerger - Starting run
07:33:10 INFO cli.engine.DefaultMerger - Merging: epiphany-cluster name: default
07:33:10 INFO cli.engine.DefaultMerger - Merging: infrastructure/machine name: single-machine
07:33:10 INFO cli.engine.DefaultMerger - Run done in 17ms
07:33:10 INFO cli.engine.SchemaValidator - Starting run
07:33:10 INFO cli.engine.SchemaValidator - Validating: epiphany-cluster
07:33:10 INFO cli.engine.SchemaValidator - Validating: infrastructure/machine
07:33:10 WARNING cli.engine.SchemaValidator - No specification validation for infrastructure/machine
07:33:10 INFO cli.engine.SchemaValidator - Run done in 6ms
07:33:10 INFO cli.engine.any.InfrastructureBuilder - Starting run
07:33:10 INFO cli.engine.any.InfrastructureBuilder - Run done in 0ms
07:33:10 INFO cli.engine.SchemaValidator - Starting run
07:33:10 INFO cli.engine.SchemaValidator - Validating: infrastructure/machine
07:33:10 WARNING cli.engine.SchemaValidator - No specification validation for infrastructure/machine
07:33:10 INFO cli.engine.SchemaValidator - Run done in 3ms
07:33:10 INFO cli.engine.TerraformTemplateGenerator - Starting run
07:33:10 INFO cli.engine.TerraformTemplateGenerator - Generating: epiphany-cluster ---> 000_hal-9000.tf
07:33:10 INFO cli.engine.TerraformTemplateGenerator - Run done in 1ms
07:33:10 ERROR cli.engine.EpiphanyEngine - [Errno 2] No such file or directory: '/usr/local/epicli/data/any/terraform/epiphany-cluster.j2'
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 103, in apply
    template_generator.run()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/TerraformTemplateGenerator.py", line 23, in run
    template = load_template_file(types.TERRAFORM, doc.provider, doc.kind)
  File "/usr/local/lib/python3.7/site-packages/cli/helpers/data_loader.py", line 59, in load_template_file
    with open(path_to_file, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/usr/local/epicli/data/any/terraform/epiphany-cluster.j2'
bash-5.0# ls /usr/local/epicli/data/any/
defaults    validation
bash-5.0#
```

I checked and there's no terraform directory in the `any` folder, so I tried copying the `any` folder from `data/azure/terraform` to `data/any/terraform` but I just got another error. By the way, I just cloned this repository, is there any other software required, like Terraform or Ansible? 

2. It seems to be there: `~/.local/share/virtualenvs/epicli-dLx47iJT/epicli/data`, however, for some reason it it is not pointing to that path.

```
(epicli) samir@ ~/projects/avt/epiphany/core/data/metal/epiphany-single-machine (master) $ epicli apply -f test.yaml
10:46:57 INFO config - docker_cli = False
10:46:57 INFO config - output_dir = '/home/samir/projects/avt/epiphany/core/data/metal/epiphany-single-machine/build'
10:46:57 INFO config - log_file = 'log.log'
10:46:57 INFO config - log_format = '%(asctime)s %(levelname)s %(name)s - %(message)s'
10:46:57 INFO config - log_date_format = '%H:%M:%S'
10:46:57 INFO config - log_count = 10
10:46:57 INFO config - log_type = 'plain'
10:46:57 INFO config - validate_certs = True
10:46:57 INFO cli.engine.DefaultMerger - Starting run
10:46:57 INFO cli.engine.DefaultMerger - Run done in 0ms
10:46:57 ERROR cli.engine.EpiphanyEngine - [Errno 2] No such file or directory: '/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/helpers/../../data/common/defaults/epiphany-cluster.yml'
Traceback (most recent call last):
  File "/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 96, in apply
    self.process_input_docs()
  File "/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 44, in process_input_docs
    self.input_docs = doc_merger.run()
  File "/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/engine/DefaultMerger.py", line 16, in run
    files_with_defaults = load_all_yaml_objs(types.DEFAULT, doc.provider, doc.kind)
  File "/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/helpers/data_loader.py", line 43, in load_all_yaml_objs
    return load_file_from_path(script_dir, path_to_file, file_type, kind)
  File "/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/helpers/data_loader.py", line 52, in load_file_from_path
    with open(path_to_file, 'r') as stream:
FileNotFoundError: [Errno 2] No such file or directory: '/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/helpers/../../data/common/defaults/epiphany-cluster.yml'
```

`FileNotFoundError: [Errno 2] No such file or directory: '/home/samir/.local/share/virtualenvs/epicli-dLx47iJT/lib/python3.7/site-packages/cli/helpers/../../data/common/defaults/epiphany-cluster.yml'`
is wrong.

**Comment by seriva** [comment]
1: Sorry forgot: 
epicli apply -f data.yaml --no-infra

--no-infra tells Epicli to skip the Terraform which we normally use for building op the stuff on Azure/AWS.

2:

**Comment by samiralajmovic** [comment]
Using data file

```
kind: epiphany-cluster
version: 0.3.0
title: "Epiphany cluster Config"
provider: any
name: "default"
specification:
  name: YOUR_CLUSTER_NAME
  admin_user:
    name: operations # YOUR-ADMIN-USERNAME
    key_path: /user/.ssh/epiphany-operations/id_rsa # YOUR-SSH-KEY-PATH
  components:
    single_machine:
      count: 1
      machines:
        - single-machine
---
kind: infrastructure/machine
provider: any
name: single-machine
specification:
  hostname: master    # YOUR-MACHINE-HOSTNAME
  ip: 192.168.100.101 # YOUR-MACHINE-IP
```

I got this error:
```
10:11:42 INFO config - docker_cli = True
10:11:42 INFO config - output_dir = '/shared/'
10:11:42 INFO config - log_file = 'log.log'
10:11:42 INFO config - log_format = '%(asctime)s %(levelname)s %(name)s - %(message)s'
10:11:42 INFO config - log_date_format = '%H:%M:%S'
10:11:42 INFO config - log_count = 10
10:11:42 INFO config - log_type = 'plain'
10:11:42 INFO config - validate_certs = True
10:11:42 INFO cli.engine.DefaultMerger - Starting run
10:11:42 INFO cli.engine.DefaultMerger - Merging: epiphany-cluster name: default
10:11:42 INFO cli.engine.DefaultMerger - Merging: infrastructure/machine name: single-machine
10:11:42 INFO cli.engine.DefaultMerger - Run done in 17ms
10:11:42 INFO cli.engine.SchemaValidator - Starting run
10:11:42 INFO cli.engine.SchemaValidator - Validating: epiphany-cluster
10:11:42 INFO cli.engine.SchemaValidator - Validating: infrastructure/machine
10:11:42 WARNING cli.engine.SchemaValidator - No specification validation for infrastructure/machine
10:11:42 INFO cli.engine.SchemaValidator - Run done in 6ms
10:11:42 INFO cli.engine.any.InfrastructureBuilder - Starting run
10:11:42 INFO cli.engine.any.InfrastructureBuilder - Run done in 0ms
10:11:42 INFO cli.engine.SchemaValidator - Starting run
10:11:42 INFO cli.engine.SchemaValidator - Validating: infrastructure/machine
10:11:42 WARNING cli.engine.SchemaValidator - No specification validation for infrastructure/machine
10:11:42 INFO cli.engine.SchemaValidator - Run done in 2ms
10:11:42 INFO cli.engine.ConfigurationAppender - Starting run
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/feature-mapping
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/kubernetes-master
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/applications
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/node-exporter
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/filebeat
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/kubernetes-node
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/elasticsearch
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/elasticsearch-curator
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/kibana
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/prometheus
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/grafana
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/zookeeper
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/jmx-exporter
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/kafka
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/kafka-exporter
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/haproxy
10:11:42 INFO cli.engine.ConfigurationAppender - Adding: configuration/haproxy-exporter
10:11:42 INFO cli.engine.ConfigurationAppender - Run done in 120ms
10:11:42 ERROR cli.engine.EpiphanyEngine - No such attribute: configuration
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 109, in apply
    self.process_configuration_docs()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/EpiphanyEngine.py", line 68, in process_configuration_docs
    self.configuration_docs = config_appender.run()
  File "/usr/local/lib/python3.7/site-packages/cli/engine/ConfigurationAppender.py", line 30, in run
    config_selector = component_value.configuration
  File "/usr/local/lib/python3.7/site-packages/cli/helpers/ObjDict.py", line 6, in __getattr__
    raise AttributeError("No such attribute: " + name)
AttributeError: No such attribute: configuration
bash-5.0#

```

However, I got something to run with:

```
kind: epiphany-cluster
name: default
provider: any
specification:
  admin_user:
    key_path: /user/.ssh/epiphany-operations/id_rsa
    name: operations
  components:
    kubernetes_master:
      count: 1
      machines:
      - default-k8s-master
  name: lala
title: Epiphany cluster Config
version: 0.3.0
Using

---
kind: infrastructure/machine
name: default-k8s-master
provider: any
specification:
  hostname: master
  ip: 192.168.100.100
```

Still not working but it's starting to run now at least, suspect I need to setup ssh and make sure networking works correctly. Btw, am I supposed to create my own ssh user key (/user/.ssh/epiphany-operations/id_rsa)?
```
10:05:20 INFO cli.engine.AnsibleCommand - }
10:05:20 ERROR cli.engine.AnsibleCommand - Error running: "ansible -m raw -a cat /etc/lsb-release | grep -i DISTRIB_ID | grep -i ubuntu && sudo apt-get install -y python-simplej
son || echo 'Cannot find information about Ubuntu distribution' -i /shared/lala/inventory all"
10:05:20 INFO cli.engine.AnsibleCommand - Retry running task: 1/5
10:05:30 INFO cli.engine.AnsibleCommand - Running: "ansible -m raw -a cat /etc/lsb-release | grep -i DISTRIB_ID | grep -i ubuntu && sudo apt-get install -y python-simplejson ||
echo 'Cannot find information about Ubuntu distribution' -i /shared/lala/inventory all"
```

**Comment by samiralajmovic** [comment]
Was enough to add
```
  components:
    single_machine:
      configuration: default
      count: 1
      machines:
        - single-machine
```
to the file. Was missing `configuration: default`

**Comment by samiralajmovic** [comment]
Using this data file `data.yml`:

```
kind: epiphany-cluster

version: 0.3.0
title: "Epiphany cluster Config"
provider: any
name: "default"

specification:
  name: avt-test
  admin_user:
    name: root
    key_path: id_rsa_epiphany
  components:
    kubernetes_master:
      count: 1
      machines:
      - default-k8s-master

---

kind: infrastructure/machine
name: default-k8s-master
provider: any
specification:
  hostname: avt-test
  ip: 192.168.56.100
```

And running a Virtual Box (2048 MB memory, 2 CPU's) which I can ssh into, it manages to install docker, kubernetes, docker, etc. but I get an error that says:

```
13:56:06 INFO cli.engine.AnsibleCommand - TASK [kubernetes_master : Run secrets encryption] *************************************************************************************
******************************************
13:56:07 INFO cli.engine.AnsibleCommand - FAILED - RETRYING: Run secrets encryption (5 retries left).
13:56:17 INFO cli.engine.AnsibleCommand - FAILED - RETRYING: Run secrets encryption (4 retries left).
13:56:27 INFO cli.engine.AnsibleCommand - FAILED - RETRYING: Run secrets encryption (3 retries left).
13:56:38 INFO cli.engine.AnsibleCommand - FAILED - RETRYING: Run secrets encryption (2 retries left).
13:56:49 INFO cli.engine.AnsibleCommand - FAILED - RETRYING: Run secrets encryption (1 retries left).
13:56:59 INFO cli.engine.AnsibleCommand - fatal: [avt-test]: FAILED! => {"attempts": 5, "changed": true, "cmd": "kubectl --kubeconfig=/home/root/.kube/config get secrets --all-n
amespaces -o json | kubectl replace -f -", "delta": "0:00:00.225881", "end": "2019-09-20 13:56:59.561341", "msg": "non-zero return code", "rc": 1, "start": "2019-09-20 13:56:59.
335460", "stderr": "The connection to the server localhost:8080 was refused - did you specify the right host or port?", "stderr_lines": ["The connection to the server localhost:
8080 was refused - did you specify the right host or port?"], "stdout": "", "stdout_lines": []}
13:56:59 INFO cli.engine.AnsibleCommand -
13:56:59 INFO cli.engine.AnsibleCommand - PLAY RECAP ****************************************************************************************************************************
```

**Comment by seriva** [comment]
Hey man,

Sorry for the late reply. Busy as we are preparing for release. Thanks for sticking with it:) 

You still have issues with the above or you managed to move past that? Asking since you contributed a fix for the RabbitMQ.

We also really need to improve some documentation regarding startup and singlemachine cluster I see for Epicli:)

Cheers
Luuk

**Comment by samiralajmovic** [comment]
Hey, no worries! Yeah, got it working, so should be fine for now :P

Thanks for the help!
Samir
